federation_version: =2.5.1
subgraphs:
    auth:
        routing_url: http://localhost:6120
        schema:
            file: ./apps/services/auth/src/schema.graphql
    content:
        routing_url: http://localhost:6110
        schema:
            file: ./apps/services/content/src/schema.graphql
